### ISSUE TITLE
Request: Keys to cycle through images in the current directory

### ISSUE THREAD

**Issue by mvanr** [robaho/seashore#136]
I've just discovered Seashore and I love it - thanks!

I was actually searching for a Mac alternative to Window's massively popular Irfanview, but there doesn't seem to be any such thing, even though Seascape does many things that Irfanview can't.

For me (and I suspect thousands of others), Irfanview's most salient and vital feature is its ability to navigate to the next image (by name) in the directory simply by pressing space, or to the previous image by pressing backspace.  This saves the laborious opening of each file manually, and makes batch editing or viewing a breeze.  Once you're used to editing or viewing a batch of files this way, it's really hard to get by without it.

Is there any chance you could consider adding keyboard shortcuts to Seashore for this?  It really doesn't matter which keys are used for this purpose, but you would want the action to close the existing image (prompting to save if necessary) before opening the next one.  Thanks for considering this!

**Comment by robaho** [comment]
Thank you. I'm glad you like it. Typically Seashore doesn't add 'limited use' functions like this in order to keep the complexity down - but lucky for you the Mac has already solved this problem with the awesome Finder...

All you need to do, is search in a Finder window, select the items of interest, then right-click and 'QuickLook on N Items'. You get the quick look window that allows you to navigate through the items, and you can open the item in Seashore directly from the QuickLook - if you've made Seashore the default editor.

Another option is after selecting, you can Open All with Seashore and then 'Merge All Windows' so each file will appear as a tab to allow you to easily navigate. This option doesn't work as well with lots of images or very large ones due to the memory needed.

**Comment by robaho** [comment]
You can also easily create a Short-Cut to Merge All Windows, or even a script to do the Open All and the Merge.

See https://osxdaily.com/2013/11/07/merge-windows-into-tabs-finder-mac-os-x/

**Comment by mvanr** [comment]
Thanks! I tried "QuickLook on N Items", but the Quicklook window closes s soon as I click "Open with Seashore" on the first image, so I can't scroll through and open each of them in Seashore this way.  Even if it didn't close the Quicklook window, it would be a lot more cumbersome with three mouse moves/clicks (click "next", click "open Seashore", click "close"), as opposed to one keystroke.

Opening all simultaneously is a problem, as you mentioned because of the memory overhead.

I do hope you'll still consider it, even if it's only one direction with a single addition to the Seashore file menu. For people like me who've used this feature for editing large numbers of images, it's really hard to get by without..

**Comment by robaho** [comment]
I see what you mean. An easier solution would be to do the search, select the first item - then press space to bring up the quick-look window - if you want to edit, use the 'open with seashore' otherwise press the down arrow to move to the next item. After you 'open with seashore' the finder window remains on that item, so you can advance to the next and press space. It's not more keystroke than what you are asking for - maybe not as smooth.

**Comment by robaho** [comment]
I've re-opened this as a possible enhancement, but I think using the Finder + QL is a lot more versatile. I think you might even be able to find a standalone application that integrates into the finder that does what you want - if not, maybe that's the next App I write :)

**Comment by robaho** [comment]
Actually, I found the solution... use the space-bar solution as described and then when you want to open the image in seashore, use Command-O (instead of the button in QL) - the file will open in Seashore and the quick look window will remain open and you can move the next item.

**Comment by mvanr** [comment]
That technique helps a lot, thanks! It's three keys and a click (command-o, command-w, click for QL focus, down) instead of one (space), but it's much better than all the mouse actions I was using before.  Wouldn't it be nice if one could use an app like Seashore as a QL plugin so that images open with it rather than the default viewer?  That's kind of what I'd dreamed of and a great idea for an app but I don't know enough about the Mac API to know if it's possible.  Thanks for your help!

**Comment by robaho** [comment]
Use can do this. You can make Seashore the default open for all image files and it will also be the default QL viewer. I am pretty sure if you can also use qlmanage to only set the default QL handler.
