### ISSUE TITLE
Universal Binary for Apple Silicon

### ISSUE THREAD

**Issue by thebitstick** [robaho/seashore#139]
Seashore works great through Rosetta, but a native binary would be nice!

**Comment by robaho** [comment]
Thank you for the input. It is actually a bit of work to port, and given that I don't have hardware to test on, and any donations haven't come close to even a down payment, it is doubtful.

If I am going to make an effort in this area, I will probably do a complete rewrite in a new commercial app.

**Comment by ThatGuySam** [comment]
@robaho Is this closed because you don't have a method to test it?

**Comment by robaho** [comment]
Pretty much. It’s hard to accept a PR that I have no way of testing.

**Comment by ThatGuySam** [comment]
If you can provide a list of specific features to test along with some sample files, I can create a callout for testers to create a screen recorded review of the Universal Binary.

**Comment by thebitstick** [comment]
I volunteer to test on my Mac mini M1.

**Comment by ThatGuySam** [comment]
@thebitstick That's awesome!!

**Comment by ThatGuySam** [comment]
I'm sure @robaho will have more specific things to try, but if you could post a screen recording of the following that would be a good start: 

- Show App's "Get Info"
- Launch App
- Pull up Activity Monitor with app listing **visible**
- Save file
- Load file

If you need a screen recording app you can simply have Quicktime record the screen by pressing: Command + Shift + 5

**Comment by robaho** [comment]
There is no PR to support Apple silicon. I don't have the time to create and test one. It is more than just setting some complier flags - there is some C code and other memory manipulation operations that I assume need to be changed for direct compilation.

**Comment by robaho** [comment]
As I mentioned, if I invest the time to support Apple silicon it will probably be on a completely new version written from the ground up in Swift. That being said, I will accept a PR to support Apple silicon, but the bar is very high for what needs to be included - since I can't break the App Store version.

**Comment by robaho** [comment]
I am re-opening the issue so a PR can be created against it.

**Comment by ThatGuySam** [comment]
Fair enough!

**Comment by mugsuk** [comment]
@robaho, I couldn't find a way to contact you other than through issues, to thank you so much for what you have done for Seashore. I have been using it since it was first released, then resorted to Gimp when seashore died; I have not had to open Gimp again since you resurrected this, and I use it daily. This level of quality for open source software on the Mac is phenomenal. Thanks again

**Comment by robaho** [comment]
fixed in 3.01
