### ISSUE TITLE
Paste from other image always pastes to center of current image

### ISSUE THREAD

**Issue by bruceajames** [robaho/seashore#157]
Seashore 3.0 on Mac OS Mojave 10.14.6

Paste from other image in previous version of Seashore always pasted to the center of the current view. It now pastes to center of the image instead. On large images, this is inconvenient, have to zoom out to find pasted content.

**Comment by robaho** [comment]
Interesting. But what happens if you paste a large image and you are zoomed in - it might not be able to be centered.

Still, the 'position tool' should automatically be selected after pasting - and there is a button 'zoom to fit' to ensure the layer is visible. You also have the ability to scale and position the layer with a single click to ensure it fits in the image.

**Comment by robaho** [comment]
I can see what you are saying now. I will fix and post a new version.

**Comment by bruceajames** [comment]
Yes I was pasting a small image (250x100) into a large image (6120x7920) while zoomed in and it is obvious

**Comment by robaho** [comment]
fixed in 3.02
