### ISSUE TITLE
GitHub releases and tags don't track App Store

### ISSUE THREAD

**Issue by mjgardner** [robaho/seashore#171]
Version 3.10 was published [on the App Store](https://apps.apple.com/us/app/seashore/id1448648921?mt=12) last week. There have been a dozen App Store releases since [version 3.0](https://github.com/robaho/seashore/releases/tag/v3.0) but the GitHub releases page has not kept pace. And [tags](https://github.com/robaho/seashore/tags) stop at [3.8](https://github.com/robaho/seashore/releases/tag/3.8).

**Comment by robaho** [comment]
The releases are no longer updated and users need to build and test themselves. There are other issues discussing this - mainly because it actually hurts the project due to lack of integrated crash reporting.

The repo is now up to date with 3.10.

TBH, there are multiple apps not adhering to the license and distributing illegal versions of Seashore on the App Store - so posting updates to the repo takes a backseat to actually fixing issues.
