### ISSUE TITLE
"pinch" performs a zoom-in, not a pinch

### ISSUE THREAD

**Issue by bosborne** [robaho/seashore#172]
Might be that this is just my ignorance, but I expected "pinch" to be the opposite of "bump", i.e. distorts a sub-region of the image. Instead it changes the entire image by performing a zoom-in, actually removing pixels rather than distorting.

**Comment by robaho** [comment]
I believe this is working at expected. See https://cifilter.io/CIPinchDistortion/ for a discussion of how it works. The only issue I see is that the scale should be 0-1, and I am allowing larger values. I have fixed this in 3.11 (which is why it shows 0-100% in the video)

See this [video](https://youtu.be/4tmrH31ZnzA) of the pinch distortion in Seashore. At larger scales you can see the image clearly being pinched in to the area.

But, you did uncover an issue. The "bump" distortion should allow negative scales - which I believe the effect you are looking for. I fixed this in issue #173 in 3.11 as well.
