### ISSUE TITLE
Toggle info/alert button next to layers

### ISSUE THREAD

**Issue by thoran** [robaho/seashore#189]
Presently one has to be move the mouse to the "Done" button to close the dialog. The other two buttons next to each layer, the eye and the link icons are toggles. If no changes are made in that dialog then I shouldn't be forced to move the cursor over to toggle it.

Also it might be better as an info icon (an i inside a circle) or an alert icon (an exclamation mark inside a triangle), rather than a hybrid of both.

**Comment by robaho** [comment]
Thank you for pointing that out - my old bad eyes never noticed :)

It is supposed to be an 'info' button - an 'i' with a circle around it. I will fix this in the next release.

As for auto-close without clicking 'Done' - there is the possibility to allow closure by clicking outside the dialog, or moving off. The latter would require that the dialog always appears above button instead of to the side - since otherwise the mouse starts outside the dialog to start.

**Comment by robaho** [comment]
I added a layer information panel at the bottom of the list of layers. This should give the information if not planning on making changes.
