### ISSUE TITLE
version 2.3.0 not available outside of the Mac App Store

### ISSUE THREAD

**Issue by core-code** [robaho/seashore#38]
its really nice that you got Seashore approved by Apple and available in the Mac App Store. i hope this will lead to many new users contributing to the project.

however, most tech-savy users hate the Mac App Store and wouldn't download there even if paid for doing that. since you don't seem intent on charging for Seashore ATM i think it would think it would make sense to provide a non-MacAppStore download option too (here on github?).

about issue #32, also note that while Apple requires the removal of Check For Updates, this of course only affects the MAS build. if you bring back a real download, i think it would be awesome if you also bring back the CheckForUpdates for NON-MAS builds.

**Comment by robaho** [comment]
I understand that, the problem is that it didn't seem trivial to change the entitlements for the App Store build - the 'check for updates' would require the 'client network access' to be enabled, just for this.

I'll see when I get a chance if can figure out an easy way to do so.

**Comment by robaho** [comment]
I posted the DMG, at least for the mean-time. By users downloading via 'brew' instead of the App Store, it hurts the applications visibility, especially since you can't post reviews if you haven't downloaded via the App Store. By increasing visibility, it widens the potential pool of people that might help the project out - without which it will probably die again... So please understand the side-effects of your download preference.

**Comment by vitorgalvao** [comment]
> By users downloading via 'brew' instead of the App Store, it hurts the applications visibility

Homebrew Cask maintainer here. I’m interested in why you think that is the case, as I don’t see it that way at all. In fact, we have a long running policy (one of the oldest) that [we are not a discoverability service, and that users should be familiar with what they are installing via Homebrew Cask before doing so](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

So I don’t see any reason why availability via Homebrew Cask would hurt Seashore’s visibility at all. If you install via Homebrew Cask, you already know what Homebrew Cask is.

But I’ll add that we respect developer wishes, so even if want to keep the direct download but want Seashore to not be distributed via Hombrew Cask, please do say so and we’ll remove it.

**Comment by core-code** [comment]
> If you download via brew you cannot leave a review on the App Store.

app store reviews are only a very small part of the 'marketing' that your users can do for you. a happy user is far more likely to do free marketing for you by recommending or mentioning your app. 

and by definition, someone that is forced to do something he hates (download from the Mac App Store), won't do anything for you at all. 

> Don’t get me wrong I use brew extensively but I typically don’t for things available in the App Store.

different people, different ways. i wouldn't download from the MAS even if Apple paid me to do it. i know there are others like me, even with the revised store in Mojave.

anyway, not telling you how to do things just trying to be helpful by throwing in my 2c ... i've been in the industry a long time and have never before heard your view that only users that download on the MAS are beneficial to a product or project.

**Comment by robaho** [comment]
I’m fairly certain in a future release of OSX general users will only be able to install software from the App Store, certainly only software certified by Apple. I can’t even send prerelease versions of Seashore to users and easily have them run it.

People that use brew are a small minority of the OSX user base. Probably less than 1%. And if you say regularly use brew it’s less than that. 

I don’t understand the pushback against the App Store.  Works pretty well imo. Brew is great for server side and utility command line tools.

**Comment by core-code** [comment]
> I’m fairly certain in a future release of OSX general users will only be able to install software from the App Store, certainly only software certified by Apple.

i doubt that as many people would abandon the platform the instant this happened.

> I can’t even send prerelease versions of Seashore to users and easily have them run it.

not sure why you are having troubles there, as long as its properly signed.

> People that use brew are a small minority of the OSX user base. 

thats true, but people that avoid the Mac App Store are probably the majority

> I don’t understand the pushback against the App Store.  Works pretty well imo. 

it never worked well for me, and i certainly don't want every app that i just download and try out to be permanently linked to an account i have with Apple.

**Comment by vitorgalvao** [comment]
I’d argue a tangential point (no hard data, though, so speculating), that MAS users seldom realise when an app is open-source, and thus increasing an app’s MAS popularity more likely translates in more support requests than in more help.

You could instead make the app paid in the MAS and free via direct download, thus getting financial help from one side and code help from the other. And if you mention “hey, this is paid but you can get it for free here”, more people will come to the repo.

If I recall correctly, Keka (archiving tool) and Textual (IRC tool) do something like that.

@core-code’s point that developers tend to hate the MAS is pretty widespread. So if you want help with the project, you’re doing it backwards. Developer’s aren’t going to help you or not because they saw reviews on the MAS. **You’re asking for help where the only users that can provide it don’t go**.

> People that use brew are a small minority of the OSX user base. Probably less than 1%

People with programming skills are also a small minority of the macOS user base. Even smaller is the percentage of people with programming skills *and* that will want to contribute to Seashore. I’d bet that the percentage of users that uses Homebrew and is a developer is way higher than the percentage of users that uses the MAS and is a developer.

I’d even consider betting that in raw numbers, the amount of developers that regularly run a `brew` command is higher than the amount that opens the MAS.

> I’m fairly certain in a future release of OSX general users will only be able to install software from the App Store, certainly only software certified by Apple.

Those are far from the same thing. Just last year Apple introduced notarisation for apps outside the MAS. That doesn’t look like a move to make users use the MAS. Because they know they can’t. Because the trend is for developers to leave the MAS, not to use it. Apple has made many questionable decisions as of late, but I doubt its leadership is so dumb as to effectively kill the platform by closing off anyone that doesn’t distribute from outside the MAS.

If only the MAS was allowed, the result wouldn’t be more apps on the MAS, it would be less people on macOS.

**Comment by robaho** [comment]
I understand your points, and I am (at least I hope to be considered one) a developer and I know full well the developer community concerns and preferences.

An app like Seashore is not a typically used by developers.

I think you are missing a BIG point. Developers don’t typically want to work on dying projects, they want to work on projects that have visibility (for their careers, others to help, or otherwise). If brew did its own marketing efforts and tracking to show “how many downloads, active installs, etc.” and spent the money to publicize these things it would be a different story. The brew community does not, and that is why many have a negative impression of brew itself.

**Comment by vitorgalvao** [comment]
> If brew did its own (…) tracking to show “how many downloads, active installs, etc.”

It does. And [the information is public](https://formulae.brew.sh/analytics/).

> and that is why many have a negative impression of brew itself.

I’ve never encountered that opinion before, so if you recall a blog post or something making that claim, I’d like to see it. Considering the outrage that followed Hombrew *introducing* analytics, I’m skeptical that many would have negative impressions of Homebrew for not providing them (which, as established, it does *and informs you of that on first install*).

**Comment by robaho** [comment]
Yes, it does, but it doesn't "promote it" in anyway that I can see. For instance, I use brew a lot, and was never notified that Seashore is now available via brew - in anyway shape or form. I wasn't even given a curtesy notice as the author that brew was now going to distribute the dmg's I provide on github. So brew is not IMO being a good citizen supporting the developers actually creating the content it "promotes" and distributes. I don't think it would be hard to surmise that there are probably many other developers that feel the same.

**Comment by vitorgalvao** [comment]
That is a fair criticism. We’ve grown enough that we’re even picky about is included, so increasing the barrier of entry to apps is a beneficial strategy. Requiring that the developer is *at least* contacted and given a reasonable amount of time (two weeks?) to refuse inclusion will ensure that only apps people *really* want get in.

Maybe require that people that submit the app also find a valid email address for Homebrew Cask maintainers to contact (with a standard message) or contact them publicly (e.g. Twitter) with a specific message and a link back to us.

I’m going to propose that to the other maintainers.

Thank you for the insight.

**Comment by vitorgalvao** [comment]
@robaho But to finish it off, should we remove Seashore from Homebrew Cask or keep it?

**Comment by core-code** [comment]
sorry to revive this topic but ... will version 3.x be available for proper download or will it be MAS-only?

cc @suschizu

**Comment by robaho** [comment]
The current plans are for version 3.0+ binaries to only be released via the App Store.
