### ISSUE TITLE
I wanted to suggest a revision to your system requirements.

### ISSUE THREAD

**Issue by Navy-Brat** [robaho/seashore#41]
Dear Mr. Engels:

Thank you so much for reviving the Seashore image editor. I have a 2008 13” Model MB402LL/A White MacBook (2.1 Ghz) with OS X 10.7.5 and I wanted to suggest a revision to your system requirements.

I'm so sorry and I was so looking forward to the new software, I downloaded and tried Seashore v0.6.6, v1.1.5, and v2.1.8 and could not get any of them to load on my system. I still use Seashore 0.5.1 which, though buggy, works on both this MacBook as well as another with OS X 10.6.8 on it. Is there a chance of making one of them compatible with either OS X 10.7.5 or  10.6.8? 

I think you made a great choice taking Seashore 0.5.1 off your websites because it is buggy and will reflect badly on the new Seashore 2.3.0. 

There's another issue I have: the number of websites that point to Seashore is very confusing. https://sourceforge.net/projects/seashore/ has a little link at the top that says “As of 2018-12-19, the new project can be found here” and that leads to a very confusing technicall-based website https://github.com/robaho/seashore whichh has no download and neither mention that the latest version of your app is on the Mac App Store.

MacUpdate still lists the developer as Mark Pazzolli Software https://www.macupdate.com/app/mac/15662/seashore and never mentions the Mac App Store. But you can directly download Seashore 2.3.0 from it without the Apple site.

In addition, Wikipedia has several links for your app at the bottom of the page (https://en.wikipedia.org/wiki/Seashore_%28software%29) and some of them work ad some of them don’t, but it is the only site I seen that mentions that your app is on the Mac App Store

Thank you for all of your hard work and I wish you the greatest success. Take care.

**Comment by robaho** [comment]
The latest 2.3.2 release should work on 10.7+. It is available now here in the 'releases'. It should be on the App Store in a few days - I recommend you wait for this. (The "technical website" you are referring to is where you just posted this issue- go to the releases tab)).

(the only way to get it to work on 10.6.8 would be to use 0.6.6 - which you say isn't working - it would require some effort to fix most likely).

I agree about the number of confusing websites - but I can't control it - I wish I could. I've debated pulling all releases except for the app store, but I'm afraid those "other websites" will just keep distributing the old version, along with any bugs it might have.... bummer but I don't know what else to do. 

I fixed the Wiki page so that all of the links work, and updated the version numbers.

If you get the latest 2.3.2 and it doesn't work on your 10.7+ OSX, please file an issue here, and include the crash details.

Thank you for the kind appreciation and well wishes.

**Comment by robaho** [comment]
2.3.2 is in the app store now. It should work with your 10.7 install.

**Comment by robaho** [comment]
@Navy-Brat if you get 2.3.2 from the App Store and it works (or doesnt...) if you could report bac on this issue I would appreciate it.

**Comment by robaho** [comment]
@navy-brat you will need version 2.3.3, 2.3.2 is broken
