### ISSUE TITLE
Corrupted file?

### ISSUE THREAD

**Issue by Major1ty** [robaho/seashore#46]
I downloaded seashoredmg.dmg from the SourceForge page at https://sourceforge.net/projects/seashore/

However, attempting to open it generates a warning: "no mountable file systems"

This usually means a corrupted download, but repeating the download had no effect. Is the original corrupted at SourceForge, perhaps?

**Comment by robaho** [comment]
Only the old 0.x version is valid at sourceforge. The latest should open with a readme asking the user to get it from the App Store. You can download DMGs from GitHub (here) under the ‘releases’.

**Comment by follower** [comment]
Side note: These days a  "no mountable file systems" error often means that the `.dmg` file was created on a version of macOS that defaults to `APFS` format rather than `HFS+` as supported by older OS versions.

(The default disk format that `hdiutil` creates (silently) depends on the format of the source drive rather than being specified explicitly--which leads people to not realise they've created a non-backwards compatbile `.dmg`--even if the application on the disk *is* backwards compatible.)

I've got a few more notes [here](http://www.labradoc.com/i/follower/p/notes-mac-os-x#20190220) but didn't get around to documenting how it's possible to extract the files on older versions. (You can confirm the disk format without being able to open it, as a `.dmg` image actually has an XML document appended to the end of the file which will contain the string `APFS` if it uses that disk format.)

**Comment by robaho** [comment]
@follower Thanks. I had already corrected this - the current builds of the dmg are HFS+. I also went back and converted the 0.6.6 version to HFS+ on Sourceforge.

**Comment by follower** [comment]
Yeah, I didn't make clear that I'd realised you'd already remedied the situation--my primary intention was to provide some addition context for @Major1ty in case they encountered the situation again with a different project. :)

BTW, thanks for your work on "resurrecting" Seashore--I was very surprised when I got an update notification the other day! I've found it a nice lightweight & fast loading image editing tool so it's nice that it hasn't been abandoned entirely!
