### ISSUE TITLE
if seashore can't read file, it won't open

### ISSUE THREAD

**Issue by KlaraPromociones** [robaho/seashore#78]
The program worked fine for a while.
Now I cannot open. No error message prompts.
The icon seems to appear at the dock of my McBook Air for a fraction of a second and then disappears again.
I tried to uninstall and reinstall, restarted the computer.
Seashore stopped working.

**Comment by robaho** [comment]
This can be caused because the last opened document is causing it to crash. I am working on a fix for that, but in the meantime do you know how to use the Console to view the log?if you could paste the crash information here I might be able to help? Also, did you download from the App Store? Are you using the crash reporter? Sorry for the problems.

**Comment by robaho** [comment]
If you delete the Seashore preferences file you should be able to open it.

**Comment by robaho** [comment]
I think the easiest way will be to hold down the shift key while opening Seashore - this should stop it from trying to restore the previous files.

**Comment by robaho** [comment]
fixed in 2.4.10 - be more defensive in opening images
